namespace shader_editor {
const char* const DefaultFragmentShaderSource =
    "#ifdef GL_ES\n"
    "precision mediump float;\n"
    "#endif\n"
    "\n"
    "uniform float time;\n"
    "uniform vec2 mouse;\n"
    "uniform vec2 resolution;\n"
    "\n"
    "// original: https://github.com/mrdoob/glsl-sandbox\n"
    "void main(void) {\n"
    "    vec2 position = (gl_FragCoord.xy / resolution.xy) + mouse / 4.0;\n"
    "\n"
    "    float color = 0.0;\n"
    "    color += sin(position.x * cos(time / 15.0) * 80.0) +\n"
    "             cos(position.y * cos(time / 15.0) * 10.0);\n"
    "    color += sin(position.y * sin(time / 10.0) * 40.0) +\n"
    "             cos(position.x * sin(time / 25.0) * 40.0);\n"
    "    color += sin(position.x * sin(time / 5.0) * 10.0) +\n"
    "             sin(position.y * sin(time / 35.0) * 80.0);\n"
    "    color *= sin(time / 10.0) * 0.5;\n"
    "\n"
    "    gl_FragColor =\n"
    "        vec4(vec3(color, color * 0.5, sin(color + time / 3.0) * 0.75), \n"
    "1.0);\n"
    "}\n";

const char* const DefaultVertexShaderSource =
    "#version 310 es\n"
    "\n"
    "layout(location=0) in vec3 aPosition;\n"
    "\n"
    "void main(void) {\n"
    "    gl_Position = vec4(aPosition, 1.0);\n"
    "}\n";

const char* const DefaultCopyShaderSource =
    "#version 310 es\n"
    "precision mediump float;\n"
    "\n"
    "layout(location=0) uniform vec2 resolution;\n"
    "layout(location=1) uniform sampler2D backbuffer;\n"
    "\n"
    "layout(location=0) out vec4 fragColor;\n"
    "\n"
    "void main(void) {\n"
    "    vec2 uv = gl_FragCoord.xy / resolution;\n"
    "    vec3 color = texture(backbuffer, uv).rgb;\n"
    "    fragColor = vec4(color, 1.0);\n"
    "}\n";

const char* const ShaderToyTemplate =
    "#version 310 es\n"
    "\n"
    "#extension GL_GOOGLE_include_directive : enable\n"
    "\n"
    "precision highp float;\n"
    "precision highp int;\n"
    "precision mediump sampler3D;\n"
    "\n"
    "layout(location=0) uniform float iTime;\n"
    "layout(location=1) uniform int iFrame;\n"
    "layout(location=2) uniform vec4 iMouse;\n"
    "layout(location=3) uniform vec2 iResolution;\n"
    "\n"
    "layout(location=4) uniform sampler2D iChannel0;\n"
    "layout(location=5) uniform sampler2D iChannel1;\n"
    "layout(location=6) uniform sampler2D iChannel2;\n"
    "layout(location=7) uniform sampler2D iChannel3;\n"
    "\n"
    "layout(location=0) out vec4 outColor;\n"
    "\n"
    "void mainImage(out vec4 fragColor, in vec2 fragCoord);\n"
    "\n"
    "void main(void) {\n"
    "    vec4 color = vec4(0.0, 0.0, 0.0, 1.0);\n"
    "    mainImage(color, gl_FragCoord.xy);\n"
    "    color.a = 1.0;\n"
    "    outColor = color;\n"
    "}\n"
    "\n"
    "#include <content>\n";
}  // namespace shader_editor
